homepage: "https://www.openssl.org/"
language: c++
primary_contact: "kurt@roeckx.be"
auto_ccs:
 - "openssl-security@openssl.org"
 - "matt@openssl.org"
 - "richard@levitte.org"
 - "tomas@openssl.org"
 - "hlandau@openssl.org"
 - "paulidale@openssl.org"
 - "nhorman@openssl.org"
 - "tjh@openssl.org"
 - "tjh@cryptsoft.com"
 - "jiatan@gmail.com"
sanitizers:
 - address
 - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/openssl/openssl.git'
fuzzing_engines:
 - afl
 - honggfuzz
